spring:
  cache:
    caffeine:
      ## forget after 60 s
      spec: expireAfterWrite=60s
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: twitch
      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            loggerLevel: basic
            default-request-headers:
              Client-Id: ${TWITCH_CLIENT_ID}
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: ${TWITCH_CLIENT_ID}
            client-secret: ${TWITCH_CLIENT_SECRET}
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token
  ## how to connect mySQL
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DATABASE_PORT:3306}/twitch?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root} # twitch official username
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # create database by providing the schema-location
  sql:
    init:
      mode: ${DATABASE_INIT:always}
      schema-locations: "classpath:database-init.sql"
logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE # Incoming http requests
    com.laioffer.twitch.external.TwitchApiClient: DEBUG
    org.springframework.jdbc.core: DEBUG # SQL
    org.springframework.jdbc.datasource.init: DEBUG

